const characterPersonality = [
  "What words or phrases do they overuse?",
  "Do they have a catchphrase?",
  "Are they more optimistic or pessimistic?",
  "Are they introverted or extroverted?",
  "Do they ever put on airs?",
  "What bad habits do they have?",
  "What makes them laugh out loud?",
  "How do they display affection?",
  "Mental handicaps?",
  "How do they want to be seen by others?",
  "How do they see themselves?",
  "How are they seen by others?",
  "Strongest character trait?",
  "Weakest character trait?",
  "How competitive are they?",
  "Do they make snap judgments or take time to consider?",
  "How do they react to praise?",
  "How do they react to criticism?",
  "What is their greatest fear?",
  "What are their biggest secrets?",
  "What is their philosophy of life?",
  "When was the last time they cried?",
  "What haunts them?",
  "What are their political views?",
  "What will they stand up for?",
  "Who do they quote?",
  "Are they indoorsy or outdoorsy?",
  "What is their sinful little habit?",
  "What sense do they most rely on?",
  "How do they treat people better than them?",
  "How do they treat people worse than them?",
  "What quality do they most value in a friend?",
  "What do they consider an overrated virtue?",
  "If they could change one thing about themselves, what would it be?",
  "What is their obsession?",
  "What are their peeves?",
  "What are their idiosyncracies?",
];

export default characterPersonality;
