const characterAppearance = [
  "Height?",
  "Weight?",
  "Build?",
  "Hair Color?",
  "Hair Style?",
  "Eye Color?",
  "Glasses or Contact Lenses?",
  "Distinguishing Facial Features?",
  "Which Facial Feature is Most Prominent?",
  "Which Bodily Feature is Most Prominent?",
  "Other Distinguishing Features?",
  "Skin?",
  "Hands?",
  "Make Up?",
  "Scars",
  "Birthmarks?",
  "Tattoos?",
  "Physical Handicaps?",
  "Type of Clothes?",
  "How Do They Wear Their Clothes?",
  "What are Their Feet Like? (type of shoes, state of shoes, socks, feet, pristine, dirty, worn, etc.",
  "Race / Ethnicity?",
  "Mannerisms?",
  "Are They in Good Health?",
  "Do they Have Any Disabilities?",
];

export default characterAppearance;
