const locationGovernment = [
  "What is the basic form of government?",
  "Who is / are the ruler / rulers?",
  "Are there parties in government? If so, what are they?",
  "What sorts of rivalry exist between the varioua people in government?",
  "Who is / are appointed to help the ruler? What are they called?",
  "How much influence does religion have on government?",
  "Do they have freedom of speech?",
  "Do they have freedom of religion?",
  "Do they have the freedom to petition?",
  "Do they have freedom of the press?",
  "Do freedoms / rights vary from class to class?",
  "What is considered illegal?",
  "Are there trials, or is justice a powerful-people-point-and-hit-affair? If there are trials, are they by jury or by some other method?",
  "In whose hands is the power to dub someone guilty or not?",
  "What sort of punishments are there?",
  "Does this culture condone torture? If so, is it as a punishment, an interrogation method, or both?",
  "Does the culture have rules against / for cruel and unusual punishment?",
  "How is the death penalty viewed?",
  "Who is responsible for catching criminals?",
  "Are there lawyers? If so, how important are they?",
  "How is mob justice viewed?",
  "How are alleged criminals treated before and after their trial (if a trial is given)?",
];

export default locationGovernment;
