const locationMilitary = [
  "Do they have an army / navy / air force? If so, which ones and why?",
  "Is the military hierarchal? If so, what are the levels?",
  "How often do they wage war?",
  "Who is the military made up of (commoners, a militia, trained soldiers)?",
  "Do people need to go through training to be in the military?",
  "What kind of weaponry do they have?",
  "What kind of vehicles do they use in fighting?",
  "How do they fight?",
  "What psychological effects does war have on this species?",
  'Are "normal" people allowed to carry weapons, or is it something exclusive to the soldiers?',
  "What major war weapons are available? (atomic bombs, cannons, trebuchets)?",
  "Do soldiers get paid for being in the military?",
  "Is the army gender-, age-, or disability-biased? Is it biased in any other ways?",
];
