from .db import db, environment, SCHEMA, add_prefix_for_prod


class BookQuestionnaire(db.Model):
    __tablename__ = 'book_questionnaires'

    if environment == "production":
        __table_args__ = {'schema': SCHEMA}

    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey(add_prefix_for_prod("users.id"), ondelete="CASCADE"), nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey(add_prefix_for_prod("books.id"), ondelete="CASCADE"), nullable=False)
    goals_one = db.Column(db.String(5000))
    goals_two = db.Column(db.String(5000))
    goals_three = db.Column(db.String(5000))
    goals_four = db.Column(db.String(5000))
    goals_five = db.Column(db.String(5000))
    goals_six = db.Column(db.String(5000))
    goals_seven = db.Column(db.String(5000))
    goals_eight = db.Column(db.String(5000))
    goals_nine = db.Column(db.String(5000))
    motivations_one = db.Column(db.String(5000))
    motivations_two = db.Column(db.String(5000))
    motivations_three = db.Column(db.String(5000))
    motivations_four = db.Column(db.String(5000))
    motivations_five = db.Column(db.String(5000))
    motivations_six = db.Column(db.String(5000))
    motivations_seven = db.Column(db.String(5000))
    motivations_eight = db.Column(db.String(5000))
    motivations_nine = db.Column(db.String(5000))
    motivations_ten = db.Column(db.String(5000))
    conflict_one = db.Column(db.String(5000))
    conflict_two = db.Column(db.String(5000))
    conflict_three = db.Column(db.String(5000))
    conflict_four = db.Column(db.String(5000))
    conflict_five = db.Column(db.String(5000))
    conflict_six = db.Column(db.String(5000))
    conflict_seven = db.Column(db.String(5000))
    conflict_eight = db.Column(db.String(5000))
    conflict_nine = db.Column(db.String(5000))
    conflict_ten = db.Column(db.String(5000))
    plot_one = db.Column(db.String(5000))
    plot_two = db.Column(db.String(5000))
    plot_three = db.Column(db.String(5000))
    plot_four = db.Column(db.String(5000))
    plot_five = db.Column(db.String(5000))
    plot_six = db.Column(db.String(5000))
    plot_seven = db.Column(db.String(5000))
    plot_eight = db.Column(db.String(5000))
    plot_nine = db.Column(db.String(5000))
    plot_ten = db.Column(db.String(5000))
    plot_eleven = db.Column(db.String(5000))
    unknown_one = db.Column(db.String(5000))
    unknown_two = db.Column(db.String(5000))
    unknown_three = db.Column(db.String(5000))
    unknown_four = db.Column(db.String(5000))
    unknown_five = db.Column(db.String(5000))
    unknown_six = db.Column(db.String(5000))
    unknown_seven = db.Column(db.String(5000))
    unknown_eight = db.Column(db.String(5000))
    unknown_nine = db.Column(db.String(5000))
    unknown_ten = db.Column(db.String(5000))
    unknown_eleven = db.Column(db.String(5000))
    unknown_twelve = db.Column(db.String(5000))
    middle_one = db.Column(db.String(5000))
    middle_two = db.Column(db.String(5000))
    middle_three = db.Column(db.String(5000))
    middle_four = db.Column(db.String(5000))
    middle_five = db.Column(db.String(5000))
    middle_six = db.Column(db.String(5000))
    middle_seven = db.Column(db.String(5000))
    middle_eight = db.Column(db.String(5000))
    middle_nine = db.Column(db.String(5000))
    middle_ten = db.Column(db.String(5000))
    end_one = db.Column(db.String(5000))
    end_two = db.Column(db.String(5000))
    end_three = db.Column(db.String(5000))
    end_four = db.Column(db.String(5000))
    end_five = db.Column(db.String(5000))
    end_six = db.Column(db.String(5000))
    end_seven = db.Column(db.String(5000))
    end_eight = db.Column(db.String(5000))
    end_nine = db.Column(db.String(5000))
    end_ten = db.Column(db.String(5000))
    turning_one = db.Column(db.String(5000))
    turning_two = db.Column(db.String(5000))
    turning_three = db.Column(db.String(5000))
    turning_four = db.Column(db.String(5000))
    turning_five = db.Column(db.String(5000))
    turning_six = db.Column(db.String(5000))
    turning_seven = db.Column(db.String(5000))
    turning_eight = db.Column(db.String(5000))
    turning_nine = db.Column(db.String(5000))
    turning_ten = db.Column(db.String(5000))
    comedy_one = db.Column(db.String(5000))
    comedy_two = db.Column(db.String(5000))
    comedy_three = db.Column(db.String(5000))
    comedy_four = db.Column(db.String(5000))
    comedy_five = db.Column(db.String(5000))
    comedy_six = db.Column(db.String(5000))
    comedy_seven = db.Column(db.String(5000))
    comedy_eight = db.Column(db.String(5000))
    comedy_nine = db.Column(db.String(5000))
    comedy_ten = db.Column(db.String(5000))
    monster_one = db.Column(db.String(5000))
    monster_two = db.Column(db.String(5000))
    monster_three = db.Column(db.String(5000))
    monster_four = db.Column(db.String(5000))
    monster_five = db.Column(db.String(5000))
    monster_six = db.Column(db.String(5000))
    monster_seven = db.Column(db.String(5000))
    monster_eight = db.Column(db.String(5000))
    monster_nine = db.Column(db.String(5000))
    monster_ten = db.Column(db.String(5000))
    voyage_one = db.Column(db.String(5000))
    voyage_two = db.Column(db.String(5000))
    voyage_three = db.Column(db.String(5000))
    voyage_four = db.Column(db.String(5000))
    voyage_five = db.Column(db.String(5000))
    voyage_six = db.Column(db.String(5000))
    voyage_seven = db.Column(db.String(5000))
    voyage_eight = db.Column(db.String(5000))
    voyage_nine = db.Column(db.String(5000))
    voyage_ten = db.Column(db.String(5000))
    quest_one = db.Column(db.String(5000))
    quest_two = db.Column(db.String(5000))
    quest_three = db.Column(db.String(5000))
    quest_four = db.Column(db.String(5000))
    quest_five = db.Column(db.String(5000))
    quest_six = db.Column(db.String(5000))
    quest_seven = db.Column(db.String(5000))
    quest_eight = db.Column(db.String(5000))
    quest_nine = db.Column(db.String(5000))
    quest_ten = db.Column(db.String(5000))
    tragedy_one = db.Column(db.String(5000))
    tragedy_two = db.Column(db.String(5000))
    tragedy_three = db.Column(db.String(5000))
    tragedy_four = db.Column(db.String(5000))
    tragedy_five = db.Column(db.String(5000))
    tragedy_six = db.Column(db.String(5000))
    tragedy_seven = db.Column(db.String(5000))
    tragedy_eight = db.Column(db.String(5000))
    tragedy_nine = db.Column(db.String(5000))
    tragedy_ten = db.Column(db.String(5000))
    rebirth_one = db.Column(db.String(5000))
    rebirth_two = db.Column(db.String(5000))
    rebirth_three = db.Column(db.String(5000))
    rebirth_four = db.Column(db.String(5000))
    rebirth_five = db.Column(db.String(5000))
    rebirth_six = db.Column(db.String(5000))
    rebirth_seven = db.Column(db.String(5000))
    rebirth_eight = db.Column(db.String(5000))
    rebirth_nine = db.Column(db.String(5000))
    rebirth_ten = db.Column(db.String(5000))
    beginning_one = db.Column(db.String(5000))
    beginning_two = db.Column(db.String(5000))
    beginning_three = db.Column(db.String(5000))
    beginning_four = db.Column(db.String(5000))
    beginning_five = db.Column(db.String(5000))
    beginning_six = db.Column(db.String(5000))
    beginning_seven = db.Column(db.String(5000))
    beginning_eight = db.Column(db.String(5000))
    beginning_nine = db.Column(db.String(5000))
    beginning_ten = db.Column(db.String(5000))
    rags_one = db.Column(db.String(5000))
    rags_two = db.Column(db.String(5000))
    rags_three = db.Column(db.String(5000))
    rags_four = db.Column(db.String(5000))
    rags_five = db.Column(db.String(5000))
    rags_six = db.Column(db.String(5000))
    rags_seven = db.Column(db.String(5000))
    rags_eight = db.Column(db.String(5000))
    rags_nine = db.Column(db.String(5000))
    rags_ten = db.Column(db.String(5000))

    def to_dict(self):
        return {
            'id': self.id,
            'author_id': self.author_id,
            'book_id': self.book_id,
            'goals': [self.goals_one, self.goals_two, self.goals_three, self.goals_four, self.goals_five, self.goals_six, self.goals_seven, self.goals_eight, self.goals_nine],
            'motivations': [self.motivations_one, self.motivations_two, self.motivations_three, self.motivations_four, self.motivations_five, self.motivations_six, self.motivations_seven, self.motivations_eight, self.motivations_nine, self.motivations_ten],
            'plot_setting': [self.plot_one, self.plot_two, self.plot_three, self.plot_four, self.plot_five, self.plot_six, self.plot_seven, self.plot_eight, self.plot_nine, self.plot_ten, self.plot_eleven],
            'conflict': [self.conflict_one, self.conflict_two, self.conflict_three, self.conflict_four, self.conflict_five, self.conflict_six, self.conflict_seven, self.conflict_eight, self.conflict_nine, self.conflict_ten],
            'mystery_unknowns': [self.unknown_one, self.unknown_two, self.unknown_three, self.unknown_four, self.unknown_five, self.unknown_six, self.unknown_seven, self.unknown_eight, self.unknown_nine, self.unknown_ten, self.unknown_eleven, self.unknown_twelve],
            'beginning': [self.beginning_one, self.beginning_two, self.beginning_three, self.beginning_four, self.beginning_five, self.beginning_six, self.beginning_seven, self.beginning_eight, self.beginning_nine, self.beginning_ten],
            'turning_points': [self.turning_one, self.turning_two, self.turning_three, self.turning_four, self.turning_five, self.turning_six, self.turning_seven, self.turning_eight, self.turning_nine, self.turning_ten],
            'middle': [self.middle_one, self.middle_two, self.middle_three, self.middle_four, self.middle_five, self.middle_six, self.middle_seven, self.middle_eight, self.middle_nine, self.middle_ten],
            'ending': [self.end_one, self.end_two, self.end_three, self.end_four, self.end_five, self.end_six, self.end_seven, self.end_eight, self.end_nine, self.end_ten],
            'rags_riches': [self.rags_one, self.rags_two, self.rags_three, self.rags_four, self.rags_five, self.rags_six, self.rags_seven, self.rags_eight, self.rags_nine, self.rags_ten],
            'overcoming_monster': [self.monster_one, self.monster_two, self.monster_three, self.monster_four, self.monster_five, self.monster_six, self.monster_seven, self.monster_eight, self.monster_nine, self.monster_ten],
            'voyage_return': [self.voyage_one, self.voyage_two, self.voyage_three, self.voyage_four, self.voyage_five, self.voyage_six, self.voyage_seven, self.voyage_eight, self.voyage_nine, self.voyage_ten],
            'quest': [self.quest_one, self.quest_two, self.quest_three, self.quest_four, self.quest_five, self.quest_six, self.quest_seven, self.quest_eight, self.quest_nine, self.quest_ten],
            'comedy': [self.comedy_one, self.comedy_two, self.comedy_three, self.comedy_four, self.comedy_five, self.comedy_six, self.comedy_seven, self.comedy_eight, self.comedy_nine, self.comedy_ten],
            'tragedy': [self.tragedy_one, self.tragedy_two, self.tragedy_three, self.tragedy_four, self.tragedy_five, self.tragedy_six, self.tragedy_seven, self.tragedy_eight, self.tragedy_nine, self.tragedy_ten],
            'rebirth': [self.rebirth_one, self.rebirth_two, self.rebirth_three, self.rebirth_four, self.rebirth_five, self.rebirth_six, self.rebirth_seven, self.rebirth_eight, self.rebirth_nine, self.rebirth_ten]
        }
