from .db import db, environment, SCHEMA, add_prefix_for_prod


class LocationQuestionnaire(db.Model):
    __tablename__ = 'location_questionnaires'

    if environment == "production":
        __table_args__ = {'schema': SCHEMA}

    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey(add_prefix_for_prod("users.id"), ondelete="CASCADE"), nullable=False)
    book_id = db.Column(db.Integer, db.ForeignKey(add_prefix_for_prod("books.id"), ondelete="CASCADE"), nullable=False)
    animals_one = db.Column(db.String(5000))
    animals_two = db.Column(db.String(5000))
    animals_three = db.Column(db.String(5000))
    animals_four = db.Column(db.String(5000))
    animals_five = db.Column(db.String(5000))
    climate_one = db.Column(db.String(5000))
    climate_two = db.Column(db.String(5000))
    climate_three = db.Column(db.String(5000))
    climate_four = db.Column(db.String(5000))
    climate_five = db.Column(db.String(5000))
    fashion_one = db.Column(db.String(5000))
    fashion_two = db.Column(db.String(5000))
    fashion_three = db.Column(db.String(5000))
    fashion_four = db.Column(db.String(5000))
    fashion_five = db.Column(db.String(5000))
    fashion_six = db.Column(db.String(5000))
    fashion_seven = db.Column(db.String(5000))
    fashion_eight = db.Column(db.String(5000))
    fashion_nine = db.Column(db.String(5000))
    fashion_ten = db.Column(db.String(5000))
    fashion_eleven = db.Column(db.String(5000))
    fashion_twelve = db.Column(db.String(5000))
    fashion_thirteen = db.Column(db.String(5000))
    fashion_fourteen = db.Column(db.String(5000))
    fashion_fifteen = db.Column(db.String(5000))
    fashion_sixteen = db.Column(db.String(5000))
    fashion_seventeen = db.Column(db.String(5000))
    fashion_eighteen = db.Column(db.String(5000))
    fashion_nineteen = db.Column(db.String(5000))
    life_one = db.Column(db.String(5000))
    life_two = db.Column(db.String(5000))
    life_three = db.Column(db.String(5000))
    life_four = db.Column(db.String(5000))
    life_five = db.Column(db.String(5000))
    life_six = db.Column(db.String(5000))
    life_seven = db.Column(db.String(5000))
    life_eight = db.Column(db.String(5000))
    death_one = db.Column(db.String(5000))
    death_two = db.Column(db.String(5000))
    death_three = db.Column(db.String(5000))
    death_four = db.Column(db.String(5000))
    economy_one = db.Column(db.String(5000))
    economy_two = db.Column(db.String(5000))
    economy_three = db.Column(db.String(5000))
    economy_four = db.Column(db.String(5000))
    economy_five = db.Column(db.String(5000))
    economy_six = db.Column(db.String(5000))
    economy_seven = db.Column(db.String(5000))
    economy_eight = db.Column(db.String(5000))
    economy_nine = db.Column(db.String(5000))
    economy_ten = db.Column(db.String(5000))
    economy_eleven = db.Column(db.String(5000))
    education_one = db.Column(db.String(5000))
    education_two = db.Column(db.String(5000))
    education_three = db.Column(db.String(5000))
    education_four = db.Column(db.String(5000))
    education_five = db.Column(db.String(5000))
    education_six = db.Column(db.String(5000))
    education_seven = db.Column(db.String(5000))
    environment_one = db.Column(db.String(5000))
    environment_two = db.Column(db.String(5000))
    environment_three = db.Column(db.String(5000))
    ethics_one = db.Column(db.String(5000))
    ethics_two = db.Column(db.String(5000))
    ethics_three = db.Column(db.String(5000))
    ethics_four = db.Column(db.String(5000))
    ethics_five = db.Column(db.String(5000))
    ethics_six = db.Column(db.String(5000))
    food_one = db.Column(db.String(5000))
    food_two = db.Column(db.String(5000))
    food_three = db.Column(db.String(5000))
    food_four = db.Column(db.String(5000))
    food_five = db.Column(db.String(5000))
    food_six = db.Column(db.String(5000))
    food_seven = db.Column(db.String(5000))
    food_eight = db.Column(db.String(5000))
    food_nine = db.Column(db.String(5000))
    food_ten = db.Column(db.String(5000))
    food_eleven = db.Column(db.String(5000))
    food_twelve = db.Column(db.String(5000))
    food_thirteen = db.Column(db.String(5000))
    food_fourteen = db.Column(db.String(5000))
    food_fifteen = db.Column(db.String(5000))
    food_sixteen = db.Column(db.String(5000))
    food_seventeen = db.Column(db.String(5000))
    food_eighteen = db.Column(db.String(5000))
    food_nineteen = db.Column(db.String(5000))
    food_twenty = db.Column(db.String(5000))
    food_twenty_one = db.Column(db.String(5000))
    food_twenty_two = db.Column(db.String(5000))
    gender_one = db.Column(db.String(5000))
    gender_two = db.Column(db.String(5000))
    gender_three = db.Column(db.String(5000))
    gender_four = db.Column(db.String(5000))
    gender_five = db.Column(db.String(5000))
    government_one = db.Column(db.String(5000))
    government_two = db.Column(db.String(5000))
    government_three = db.Column(db.String(5000))
    government_four = db.Column(db.String(5000))
    government_five = db.Column(db.String(5000))
    government_six = db.Column(db.String(5000))
    government_seven = db.Column(db.String(5000))
    government_eight = db.Column(db.String(5000))
    government_nine = db.Column(db.String(5000))
    government_ten = db.Column(db.String(5000))
    government_eleven = db.Column(db.String(5000))
    government_twelve = db.Column(db.String(5000))
    government_thirteen = db.Column(db.String(5000))
    government_fourteen = db.Column(db.String(5000))
    government_fifteen = db.Column(db.String(5000))
    government_sixteen = db.Column(db.String(5000))
    government_seventeen = db.Column(db.String(5000))
    government_eighteen = db.Column(db.String(5000))
    government_nineteen = db.Column(db.String(5000))
    government_twenty = db.Column(db.String(5000))
    government_twenty_one = db.Column(db.String(5000))
    government_twenty_two = db.Column(db.String(5000))
    holidays_one = db.Column(db.String(5000))
    holidays_two = db.Column(db.String(5000))
    holidays_three = db.Column(db.String(5000))
    holidays_four = db.Column(db.String(5000))
    holidays_five = db.Column(db.String(5000))
    holidays_six = db.Column(db.String(5000))
    holidays_seven = db.Column(db.String(5000))
    holidays_eight = db.Column(db.String(5000))
    holidays_nine = db.Column(db.String(5000))
    holidays_ten = db.Column(db.String(5000))
    families_one = db.Column(db.String(5000))
    families_two = db.Column(db.String(5000))
    families_three = db.Column(db.String(5000))
    families_four = db.Column(db.String(5000))
    families_five = db.Column(db.String(5000))
    families_six = db.Column(db.String(5000))
    families_seven = db.Column(db.String(5000))
    families_eight = db.Column(db.String(5000))
    families_nine = db.Column(db.String(5000))
    families_ten = db.Column(db.String(5000))
    families_eleven = db.Column(db.String(5000))
    families_twelve = db.Column(db.String(5000))
    families_thirteen = db.Column(db.String(5000))
    families_fourteen = db.Column(db.String(5000))
    families_fifteen = db.Column(db.String(5000))
    families_sixteen = db.Column(db.String(5000))
    families_seventeen = db.Column(db.String(5000))
    families_eighteen = db.Column(db.String(5000))
    families_nineteen = db.Column(db.String(5000))
    military_one = db.Column(db.String(5000))
    military_two = db.Column(db.String(5000))
    military_three = db.Column(db.String(5000))
    military_four = db.Column(db.String(5000))
    military_five = db.Column(db.String(5000))
    military_six = db.Column(db.String(5000))
    military_seven = db.Column(db.String(5000))
    military_eight = db.Column(db.String(5000))
    military_nine = db.Column(db.String(5000))
    military_ten = db.Column(db.String(5000))
    military_eleven = db.Column(db.String(5000))
    military_twelve = db.Column(db.String(5000))
    military_thirteen = db.Column(db.String(5000))
    recreation_one = db.Column(db.String(5000))
    recreation_two = db.Column(db.String(5000))
    recreation_three = db.Column(db.String(5000))
    recreation_four = db.Column(db.String(5000))
    recreation_five = db.Column(db.String(5000))
    recreation_six = db.Column(db.String(5000))
    religion_one = db.Column(db.String(5000))
    religion_two = db.Column(db.String(5000))
    religion_three = db.Column(db.String(5000))
    religion_four = db.Column(db.String(5000))
    religion_five = db.Column(db.String(5000))
    religion_six = db.Column(db.String(5000))
    religion_seven = db.Column(db.String(5000))
    religion_eight = db.Column(db.String(5000))
    religion_nine = db.Column(db.String(5000))
    religion_ten = db.Column(db.String(5000))
    religion_eleven = db.Column(db.String(5000))
    social_one = db.Column(db.String(5000))
    social_two = db.Column(db.String(5000))
    social_three = db.Column(db.String(5000))
    social_four = db.Column(db.String(5000))
    social_five = db.Column(db.String(5000))
    social_six = db.Column(db.String(5000))
    social_seven = db.Column(db.String(5000))
    social_eight = db.Column(db.String(5000))
    social_nine = db.Column(db.String(5000))
    social_ten = db.Column(db.String(5000))
    taboos_one = db.Column(db.String(5000))
    taboos_two = db.Column(db.String(5000))
    taboos_three = db.Column(db.String(5000))
    taboos_four = db.Column(db.String(5000))
    tech_one = db.Column(db.String(5000))
    tech_two = db.Column(db.String(5000))
    tech_three = db.Column(db.String(5000))
    transportation_one = db.Column(db.String(5000))
    transportation_two = db.Column(db.String(5000))
    transportation_three = db.Column(db.String(5000))
    transportation_four = db.Column(db.String(5000))
    transportation_five = db.Column(db.String(5000))
    transportation_six = db.Column(db.String(5000))

    def to_dict(self):
        return {
            'id': self.id,
            'author_id': self.author_id,
            'book_id': self.book_id,
            'animals': [self.animals_one, self.animals_two, self.animals_three, self.animals_four, self.animals_five],
            'climate_weather': [self.climate_one, self.climate_two, self.climate_three, self.climate_four, self.climate_five],
            'clothing_fashion': [self.fashion_one, self.fashion_two, self.fashion_three, self.fashion_four, self.fashion_five, self.fashion_six, self.fashion_seven, self.fashion_eight, self.fashion_nine, self.fashion_ten, self.fashion_eleven, self.fashion_twelve, self.fashion_thirteen, self.fashion_fourteen, self.fashion_fifteen, self.fashion_sixteen, self.fashion_seventeen, self.fashion_eighteen, self.fashion_nineteen],
            'daily_life': [self.life_one, self.life_two, self.life_three, self.life_four, self.life_five, self.life_six, self.life_seven, self.life_eight],
            'death': [self.death_one, self.death_two, self.death_three, self.death_four],
            'economy': [self.economy_one, self.economy_two, self.economy_three, self.economy_four, self.economy_five, self.economy_six, self.economy_seven, self.economy_eight, self.economy_nine, self.economy_ten, self.economy_eleven],
            'education': [self.education_one, self.education_two, self.education_three, self.education_four, self.education_five, self.education_six, self.education_seven],
            'environment': [self.environment_one, self.environment_two, self.environment_three],
            'ethics': [self.ethics_one, self.ethics_two, self.ethics_three, self.ethics_four, self.ethics_five, self.ethics_six],
            'food_drink': [self.food_one, self.food_two, self.food_three, self.food_four, self.food_five, self.food_six, self.food_seven, self.food_eight, self.food_nine, self.food_ten, self.food_eleven, self.food_twelve, self.food_thirteen, self.food_fourteen, self.food_fifteen, self.food_sixteen, self.food_seventeen, self.food_eighteen, self.food_nineteen, self.food_twenty, self.food_twenty_one, self.food_twenty_two],
            'gender_sexuality': [self.gender_one, self.gender_two, self.gender_three, self.gender_four, self.gender_five],
            'government': [self.government_one, self.government_two, self.government_three, self.government_four, self.government_five, self.government_six, self.government_seven, self.government_eight, self.government_nine, self.government_ten, self.government_eleven, self.government_twelve, self.government_thirteen, self.government_fourteen, self.government_fifteen, self.government_sixteen, self.government_seventeen, self.government_eighteen, self.government_nineteen, self.government_twenty, self.government_twenty_one, self.government_twenty_two],
            'holidays_ceremonies': [self.holidays_one, self.holidays_two, self.holidays_three, self.holidays_four, self.holidays_five, self.holidays_six, self.holidays_seven, self.holidays_eight, self.holidays_nine, self.holidays_ten],
            'marriages_families': [self.families_one, self.families_two, self.families_three, self.families_four, self.families_five, self.families_six, self.families_seven, self.families_eight, self.families_nine, self.families_ten, self.families_eleven, self.families_twelve, self.families_thirteen, self.families_fourteen, self.families_fifteen, self.families_sixteen, self.families_seventeen, self.families_eighteen, self.families_nineteen],
            'military': [self.military_one, self.military_two, self.military_three, self.military_four, self.military_five, self.military_six, self.military_seven, self.military_eight, self.military_nine, self.military_ten, self.military_eleven, self.military_twelve, self.military_thirteen],
            'recreation': [self.recreation_one, self.recreation_two, self.recreation_three, self.recreation_four, self.recreation_five, self.recreation_six],
            'religion_traditions': [self.religion_one, self.religion_two, self.religion_three, self.religion_four, self.religion_five, self.religion_six, self.religion_seven, self.religion_eight, self.religion_nine, self.religion_ten, self.religion_eleven],
            'social_hierarchy': [self.social_one, self.social_two, self.social_three, self.social_four, self.social_five, self.social_six, self.social_seven, self.social_eight, self.social_nine, self.social_ten],
            'taboos': [self.taboos_one, self.taboos_two, self.taboos_three, self.taboos_four],
            'technology': [self.tech_one, self.tech_two, self.tech_three],
            'transportation': [self.transportation_one, self.transportation_two, self.transportation_three, self.transportation_four, self.transportation_five, self.transportation_six]
        }
